### ISSUE TITLE
Startup exception: Notify was imported without specifying a version first.

### ISSUE THREAD

**Issue by aurelijusrozenas** [awamper/draobpilc#10]
Hi,

```
$ gpaste-client --version
GPaste 3.20.4
$ python3.5 --version
Python 3.5.2+
```

after apt update draobpilc stopped working. Tried purging gpaste and draobpilc and reinstalling, but now I get this error:
```
/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
Traceback (most recent call last):
  File "/home/mysuser/.local/bin/draobpilc", line 11, in <module>
    load_entry_point('Draobpilc==0.2', 'gui_scripts', 'draobpilc')()
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/main.py", line 208, in run
    app = Application()
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/application.py", line 113, in __init__
    self._history_items = HistoryItems()
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/history_items.py", line 41, in __init__
    self.reload_history()
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/history_items.py", line 142, in reload_history
    new_item = HistoryItem(index)
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/history_item.py", line 57, in __init__
    if index >= 0: self.load_data(index)
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/history_item.py", line 90, in load_data
    if not self._widget: self._widget = HistoryItemView(self)
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/widgets/history_item_view.py", line 307, in __init__
    self._infobox = Infobox(self.item)
  File "/home/mysuser/.local/lib/python3.5/site-packages/draobpilc/widgets/history_item_view.py", line 107, in __init__
    pixbuf = icon_info.load_icon()
AttributeError: 'NoneType' object has no attribute 'load_icon'
```

Any ideas?

**Comment by awamper** [comment]
I can't reproduce it. Try to clear gpaste history.
> gpaste-client empty

**Comment by awamper** [comment]
I pushed the fix to master.

**Comment by aurelijusrozenas** [comment]
Sadly it still does not work. Install output:
```bash
$ sudo pip3 install git+https://github.com/awamper/draobpilc
The directory '/home/myuser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/myuser/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/awamper/draobpilc
  Cloning https://github.com/awamper/draobpilc to /tmp/pip-_dkq2mxd-build
Requirement already satisfied: humanize in /home/myuser/.local/lib/python3.5/site-packages (from Draobpilc==0.3)
Requirement already satisfied: blinker in /home/myuser/.local/lib/python3.5/site-packages (from Draobpilc==0.3)
Requirement already satisfied: python3-keybinder in /home/myuser/.local/lib/python3.5/site-packages (from Draobpilc==0.3)
Requirement already satisfied: python3-xlib in /home/myuser/.local/lib/python3.5/site-packages (from Draobpilc==0.3)
Installing collected packages: Draobpilc
  Running setup.py install for Draobpilc ... done
Successfully installed Draobpilc-0.3
```

Strangely now program does not exit but hangs on startup:
```bash
$ draobpilc
/usr/local/lib/python3.5/dist-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/local/lib/python3.5/dist-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
```

I know nothing about python, draobpilc was working before without any problems. Maybe I have some lib's with wrong version (Notify, GPaste)? I do have multiple python versions:
```bash
$ python --version
Python 2.7.12+
$ python2 --version
Python 2.7.12+
$ python3 --version
Python 3.5.2+
```

**Comment by awamper** [comment]
Try to clear gpaste history:
> gpaste-client empty

**Comment by aurelijusrozenas** [comment]
Cleared history already last time.

However after last reboot (I guess), draobpilc starts and works! Still displays error from my last comment.

So as long as it is working I am closing this issue.

Thanks for response :)
P.S. this is the best gpaste extension/plugin!
